import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { CameraView, useCameraPermissions } from 'expo-camera';
import * as FileSystem from 'expo-file-system';
import { decode } from 'base64-arraybuffer';
import * as Haptics from 'expo-haptics';
import * as ImagePicker from 'expo-image-picker';
import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useRef, useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { ensureParticipant, supabase, useApp } from '../../lib/app-context';
import { colors } from '../../lib/theme';
const PHOTO_BUCKET='photos';
export default function CameraScreen(){
  const router=useRouter();const {eventId}=useLocalSearchParams<{eventId:string}>();const {displayName}=useApp();const [perm,request]=useCameraPermissions();const [facing,setFacing]=useState<'front'|'back'>('back');const [flash,setFlash]=useState<'off'|'on'>('off');const [busy,setBusy]=useState(false);const [cameraReady,setCameraReady]=useState(false);const [message,setMessage]=useState('');const ref=useRef<CameraView>(null);
  if(!perm)return <View style={styles.center}><ActivityIndicator color="#fff"/></View>;
  if(!perm.granted)return <View style={styles.center}><MaterialCommunityIcons name="camera-outline" size={36} color="#fff"/><Text style={styles.title}>Camera access</Text><Text style={styles.sub}>Mefie needs the camera to capture and share moments.</Text><Pressable onPress={request} style={styles.cta}><Text style={styles.ctaText}>Allow camera</Text></Pressable></View>;
  const upload=async(uri:string,width?:number,height?:number)=>{if(!supabase)throw new Error('Cloud connection is not configured.');if(!eventId)throw new Error('Event ID is missing.');setMessage('Joining event…');const participantId=await ensureParticipant(String(eventId),displayName);if(!participantId)throw new Error('Could not join this event.');setMessage('Reading photo…');let localUri=uri;let temporaryUri:string|undefined;try{if(uri.startsWith('content://')){temporaryUri=`${FileSystem.cacheDirectory}mefie-upload-${Date.now()}.jpg`;await FileSystem.copyAsync({from:uri,to:temporaryUri});localUri=temporaryUri;}const info=await FileSystem.getInfoAsync(localUri,{size:true});if(!info.exists)throw new Error('The photo file no longer exists on the device.');if(!info.size)throw new Error('The captured photo is empty.');const base64=await FileSystem.readAsStringAsync(localUri,{encoding:FileSystem.EncodingType.Base64});if(!base64)throw new Error('Could not read the captured photo.');const body=decode(base64);const path=`${eventId}/${Date.now()}-${Math.random().toString(36).slice(2,10)}.jpg`;setMessage('Uploading…');const {error:uploadError}=await supabase.storage.from(PHOTO_BUCKET).upload(path,body,{contentType:'image/jpeg',upsert:false,cacheControl:'3600'});if(uploadError)throw new Error(`Photo upload failed: ${uploadError.message}`);const {data:urlData}=supabase.storage.from(PHOTO_BUCKET).getPublicUrl(path);setMessage('Saving photo…');const {error:insertError}=await supabase.from('photos').insert({event_id:eventId,participant_id:participantId,storage_path:path,original_filename:`mefie-${Date.now()}.jpg`,file_size:body.byteLength,width:width||null,height:height||null,public_url:urlData.publicUrl});if(insertError){await supabase.storage.from(PHOTO_BUCKET).remove([path]).catch(()=>undefined);throw new Error(`Photo record failed: ${insertError.message}`);}}catch(error:any){const msg=error?.message||String(error)||'Photo upload failed.';if(msg.includes('Network request failed'))throw new Error('Could not reach photo storage. Check the phone internet connection and try again.');throw error;}finally{if(temporaryUri)await FileSystem.deleteAsync(temporaryUri,{idempotent:true}).catch(()=>undefined);}};
  const capture=async()=>{if(!ref.current||busy||!cameraReady)return;setBusy(true);setMessage('');await Haptics.impactAsync(Haptics.ImpactFeedbackStyle.Light);try{await new Promise(resolve=>setTimeout(resolve,250));if(!ref.current)throw new Error('Camera is not ready.');const photo=await ref.current.takePictureAsync({quality:0.8,skipProcessing:true});if(!photo?.uri)throw new Error('Could not capture the photo.');await upload(photo.uri,photo.width,photo.height);await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success);setMessage('Shared ✓')}catch(e:any){setMessage(e?.message||'Could not capture the photo. Please try again.')}finally{setBusy(false)}};
  const pick=async()=>{if(busy)return;const permission=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!permission.granted){setMessage('Photo library permission is required.');return;}const result=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:0.9,allowsMultipleSelection:false});if(result.canceled||!result.assets?.[0])return;setBusy(true);setMessage('');try{const image=result.assets[0];await upload(image.uri,image.width,image.height);setMessage('Shared ✓');await Haptics.notificationAsync(Haptics.NotificationFeedbackType.Success)}catch(e:any){setMessage(e?.message||'Upload failed.')}finally{setBusy(false)}};
  return <View style={styles.container}><CameraView ref={ref} style={StyleSheet.absoluteFill} facing={facing} flash={flash} onCameraReady={()=>setCameraReady(true)} onMountError={error=>{setCameraReady(false);setMessage(error.message||'Could not start the camera.')}}/><View style={styles.scrimTop}/><View style={styles.top}><Pressable accessibilityLabel="Close camera" onPress={()=>router.back()} style={styles.control}><MaterialCommunityIcons name="close" size={23} color="#fff"/></Pressable><Pressable accessibilityLabel={flash==='on'?'Turn flash off':'Turn flash on'} onPress={()=>setFlash(v=>v==='off'?'on':'off')} style={styles.control}><MaterialCommunityIcons name={flash==='on'?'flash':'flash-off'} size={20} color="#fff"/></Pressable></View><View style={styles.bottom}>{message?<View style={styles.message}><MaterialCommunityIcons name="sparkles" size={15} color="#fff"/><Text style={styles.messageText}>{message}</Text></View>:null}<View style={styles.row}><Pressable accessibilityLabel="Choose photo" onPress={pick} style={styles.sideControl}><MaterialCommunityIcons name="image-outline" size={21} color="#fff"/></Pressable><Pressable accessibilityLabel="Take photo" onPress={capture} disabled={!cameraReady||busy} style={[styles.shutter,!cameraReady&&styles.shutterDisabled]}>{busy?<ActivityIndicator color="#111"/>:<View style={styles.shutterInner}><MaterialCommunityIcons name="camera-outline" size={27} color="#111"/></View>}</Pressable><Pressable accessibilityLabel="Switch camera" onPress={()=>{setCameraReady(false);setFacing(v=>v==='back'?'front':'back')}} style={styles.sideControl}><MaterialCommunityIcons name="camera-flip-outline" size={21} color="#fff"/></Pressable></View><Text style={styles.mode}>{cameraReady?'PHOTO':'STARTING CAMERA…'}</Text></View></View>;
}
const styles=StyleSheet.create({container:{flex:1,backgroundColor:'#000'},scrimTop:{position:'absolute',top:0,left:0,right:0,height:150,backgroundColor:'rgba(0,0,0,.20)'},top:{position:'absolute',top:55,left:20,right:20,flexDirection:'row',justifyContent:'space-between'},control:{width:44,height:44,borderRadius:22,backgroundColor:'rgba(16,21,27,.42)',borderWidth:1,borderColor:'rgba(255,255,255,.20)',alignItems:'center',justifyContent:'center'},bottom:{position:'absolute',bottom:28,left:0,right:0,alignItems:'center'},row:{width:'100%',flexDirection:'row',alignItems:'center',justifyContent:'space-around',paddingHorizontal:20},sideControl:{width:50,height:50,borderRadius:25,backgroundColor:'rgba(20,25,31,.45)',borderWidth:1,borderColor:'rgba(255,255,255,.20)',alignItems:'center',justifyContent:'center'},shutter:{width:82,height:82,borderRadius:41,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:2,borderColor:'rgba(255,255,255,.72)'},shutterDisabled:{opacity:.55},shutterInner:{width:70,height:70,borderRadius:35,borderWidth:2,borderColor:'#111',alignItems:'center',justifyContent:'center'},mode:{color:'#fff',fontSize:11,marginTop:10,fontWeight:'800',letterSpacing:1},message:{maxWidth:'88%',flexDirection:'row',alignItems:'center',gap:7,color:'#fff',backgroundColor:'rgba(10,14,18,.62)',paddingHorizontal:15,paddingVertical:9,borderRadius:18,borderWidth:1,borderColor:'rgba(255,255,255,.16)',marginBottom:14},messageText:{color:'#fff',fontWeight:'700',fontSize:13},center:{flex:1,backgroundColor:'#0A0F15',alignItems:'center',justifyContent:'center',padding:28},title:{color:'#fff',fontSize:28,fontWeight:'800',marginTop:14},sub:{color:colors.muted,textAlign:'center',marginTop:8,lineHeight:20},cta:{marginTop:22,backgroundColor:'#fff',paddingHorizontal:24,paddingVertical:15,borderRadius:20},ctaText:{color:'#111',fontWeight:'800'}});
