import { useLocalSearchParams, useRouter } from 'expo-router';
import React, { useEffect, useMemo, useState } from 'react';
import { Image, Pressable, StyleSheet, Text, View } from 'react-native';
import { BackButton, Screen } from '../../components/Screen';
import { GlassButton, GlassCard, IconButton } from '../../components/Glass';
import { colors } from '../../lib/theme';
import { supabase, useApp } from '../../lib/app-context';

const demoPhotos = [
  'https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=700&q=80',
  'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=700&q=80',
  'https://images.unsplash.com/photo-1501785888041-af3ef285b470?auto=format&fit=crop&w=700&q=80',
  'https://images.unsplash.com/photo-1511497584788-876760111969?auto=format&fit=crop&w=700&q=80',
  'https://images.unsplash.com/photo-1470770841072-f978cf4d019e?auto=format&fit=crop&w=700&q=80',
  'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?auto=format&fit=crop&w=700&q=80'
];
export default function EventScreen(){const router=useRouter();const {id}=useLocalSearchParams<{id:string}>();const {displayName}=useApp();const [event,setEvent]=useState<any>(null);const [photos,setPhotos]=useState<any[]>([]);const [people,setPeople]=useState<any[]>([]);
useEffect(()=>{let active=true;(async()=>{if(supabase){const [{data:e},{data:p},{data:pt}]=await Promise.all([supabase.from('events').select('*').eq('id',id).single(),supabase.from('photos').select('*').eq('event_id',id).order('created_at',{ascending:false}).limit(100),supabase.from('participants').select('*').eq('event_id',id).order('joined_at',{ascending:true})]);if(active){setEvent(e);setPhotos(p||[]);setPeople(pt||[]);}}else{setEvent({name:'Your event',status:'active'});setPhotos(demoPhotos.map((uri,i)=>({id:String(i),uri})));}})();
if(supabase){const ch=supabase.channel(`event-${id}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'photos',filter:`event_id=eq.${id}`},payload=>setPhotos(curr=>[payload.new,...curr])).on('postgres_changes',{event:'*',schema:'public',table:'participants',filter:`event_id=eq.${id}`},payload=>setPeople(curr=>{if(payload.eventType==='INSERT')return [...curr,payload.new];if(payload.eventType==='DELETE')return curr.filter(x=>x.id!==payload.old.id);return curr.map(x=>x.id===payload.new.id?payload.new:x)})).subscribe();return()=>{active=false;supabase.removeChannel(ch)}}return()=>{active=false}},[id]);
const title=event?.name||'Event';return <View style={{flex:1,backgroundColor:'#081017'}}><Screen backgroundImage={demoPhotos[1]}><View style={styles.top}><BackButton/><IconButton label="⋯"/></View><View style={styles.hero}><Text style={styles.title}>{title}</Text><Text style={styles.meta}>{people.length||event?.people||0} people · {photos.length||event?.photos||0} photos</Text><View style={{flexDirection:'row',marginTop:14}}>{people.slice(0,5).map((p,i)=><View key={p.id||i} style={styles.avatar}><Text style={{color:'#fff',fontWeight:'800'}}>{(p.display_name||displayName||'?')[0]}</Text></View>)}<View style={styles.avatar}><Text style={{color:'#fff',fontWeight:'800'}}>+</Text></View></View></View><GlassButton label="Invite" icon="↗"/><GlassCard style={{padding:5}}><View style={styles.tabs}><Text style={styles.activeTab}>Photos</Text><Text style={styles.tab}>People</Text></View><View style={styles.grid}>{photos.length?photos.map((p,i)=>{const uri=p.uri||p.preview_url||p.public_url;return <Pressable key={p.id||i} style={styles.photo} onPress={()=>router.push({pathname:'/photo/[id]',params:{id:p.id,eventId:id,index:String(i)}})}>{uri?<Image source={{uri}} style={{width:'100%',height:'100%'}}/>:<View style={{flex:1,backgroundColor:'#26313b'}}/>}</Pressable>}):<View style={{padding:26}}><Text style={{color:colors.white,fontWeight:'800'}}>No photos yet.</Text><Text style={{color:colors.muted,marginTop:5}}>Be the first to capture the moment.</Text></View>}</View></GlassCard><View style={{height:92}}/></Screen><Pressable onPress={()=>router.push({pathname:'/camera/[eventId]',params:{eventId:id}})} style={styles.camera}><Text style={{fontSize:28}}>⌾</Text></Pressable></View>}
const styles=StyleSheet.create({top:{flexDirection:'row',justifyContent:'space-between'},hero:{paddingTop:42,paddingBottom:10},title:{color:colors.white,fontSize:33,fontWeight:'800'},meta:{color:colors.muted,fontSize:14,marginTop:4},avatar:{width:33,height:33,borderRadius:16.5,backgroundColor:'#44505e',borderWidth:2,borderColor:'#0b1117',marginRight:-4,alignItems:'center',justifyContent:'center'},tabs:{flexDirection:'row',gap:10,padding:8,marginBottom:4},activeTab:{backgroundColor:'#fff',color:'#111',fontWeight:'800',paddingHorizontal:22,paddingVertical:10,borderRadius:18},tab:{color:colors.muted,fontWeight:'700',paddingHorizontal:22,paddingVertical:10},grid:{flexDirection:'row',flexWrap:'wrap',gap:4},photo:{width:'32.9%',height:112,borderRadius:10,overflow:'hidden',backgroundColor:'#26313b'},camera:{position:'absolute',bottom:24,alignSelf:'center',width:68,height:68,borderRadius:34,backgroundColor:'#fff',alignItems:'center',justifyContent:'center',borderWidth:5,borderColor:'rgba(255,255,255,.3)'}})
