import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { BottomNav, Screen } from '../components/Screen';
import { GlassCard, GlassButton, GlassInput } from '../components/Glass';
import { useApp } from '../lib/app-context';
import { colors } from '../lib/theme';
export default function You(){const router=useRouter();const {displayName,setDisplayName}=useApp();const [editing,setEditing]=useState(false);const [name,setName]=useState(displayName);return <View style={{flex:1,backgroundColor:'#0A0F15'}}><Screen><View style={{alignItems:'center',paddingTop:32}}><View style={styles.avatar}><Text style={styles.avatarText}>{displayName[0]}</Text></View><Text style={styles.title}>{displayName}</Text><Text style={styles.handle}>@{displayName.toLowerCase().replace(/\s+/g,'')}</Text></View><GlassCard><Text style={styles.row}>▣  My events <Text style={styles.chev}>›</Text></Text><View style={styles.div}/><Text style={styles.row} onPress={()=>setEditing(v=>!v)}>⚙  Settings <Text style={styles.chev}>›</Text></Text><View style={styles.div}/><Text style={styles.row}>◉  Help & feedback <Text style={styles.chev}>›</Text></Text></GlassCard>{editing?<GlassCard><GlassInput label="Display name" value={name} onChangeText={setName}/><View style={{marginTop:14}}><GlassButton primary label="Save" onPress={async()=>{await setDisplayName(name);setEditing(false)}}/></View></GlassCard>:<GlassButton label="Edit profile" onPress={()=>setEditing(true)}/>}</Screen><BottomNav active="you"/></View>}
const styles=StyleSheet.create({avatar:{width:96,height:96,borderRadius:48,backgroundColor:'rgba(255,255,255,.2)',borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:38,color:'#fff',fontWeight:'800'},title:{color:'#fff',fontSize:27,fontWeight:'800',marginTop:14},handle:{color:colors.muted,marginTop:3},row:{color:'#fff',fontSize:16,paddingVertical:5},chev:{float:'right'},div:{height:1,backgroundColor:colors.line,marginVertical:10}})
