import MaterialCommunityIcons from '@expo/vector-icons/MaterialCommunityIcons';
import { useRouter } from 'expo-router';
import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { BottomNav, Screen } from '../components/Screen';
import { GlassButton, GlassCard, GlassInput } from '../components/Glass';
import { useApp } from '../lib/app-context';
import { colors } from '../lib/theme';
export default function You(){const router=useRouter();const {displayName,setDisplayName}=useApp();const [editing,setEditing]=useState(false);const [name,setName]=useState(displayName);return <View style={styles.root}><Screen><View style={styles.profile}><View style={styles.avatar}><Text style={styles.avatarText}>{displayName[0]?.toUpperCase()||'M'}</Text></View><Text style={styles.title}>{displayName}</Text><Text style={styles.handle}>@{displayName.toLowerCase().replace(/\s+/g,'')}</Text></View><GlassCard style={styles.menu}><MenuRow icon="image-multiple-outline" label="My events" onPress={()=>router.push('/events')}/><View style={styles.div}/><MenuRow icon="cog-outline" label="Settings" onPress={()=>setEditing(v=>!v)}/><View style={styles.div}/><MenuRow icon="help-circle-outline" label="Help & feedback"/></GlassCard>{editing?<GlassCard><GlassInput label="Display name" value={name} onChangeText={setName}/><View style={{marginTop:14}}><GlassButton primary label="Save" onPress={async()=>{await setDisplayName(name);setEditing(false)}}/></View></GlassCard>:<GlassButton label="Edit profile" onPress={()=>setEditing(true)}/>}</Screen><BottomNav active="you"/></View>}
function MenuRow({icon,label,onPress}:{icon:any;label:string;onPress?:()=>void}){return <View style={styles.menuRow} onTouchEnd={onPress}><MaterialCommunityIcons name={icon} size={21} color="rgba(255,255,255,.82)"/><Text style={styles.rowText}>{label}</Text><MaterialCommunityIcons name="chevron-right" size={21} color="rgba(255,255,255,.55)"/></View>}
const styles=StyleSheet.create({root:{flex:1,backgroundColor:'#0A0F15'},profile:{alignItems:'center',paddingTop:28,paddingBottom:22},avatar:{width:100,height:100,borderRadius:50,backgroundColor:'rgba(255,255,255,.16)',borderWidth:1,borderColor:colors.lineStrong,alignItems:'center',justifyContent:'center'},avatarText:{fontSize:39,color:'#fff',fontWeight:'800'},title:{color:'#fff',fontSize:29,fontWeight:'800',marginTop:14,letterSpacing:-.5},handle:{color:colors.muted,marginTop:3,fontSize:13},menu:{paddingHorizontal:16,paddingVertical:8},menuRow:{minHeight:54,flexDirection:'row',alignItems:'center'},rowText:{flex:1,color:'#fff',fontSize:16,fontWeight:'650',marginLeft:13},div:{height:1,backgroundColor:colors.line,marginHorizontal:2}});
